### ISSUE TITLE
Search using core keyboard

### ISSUE THREAD

**Issue by MrMC** [plexinc/plex-for-kodi#165]
We are chasing an issue with running Plex for Kodi under MrMC on the AppleTV 4/4K. When we bring up the search, there's a text edit field and text keys below. If we do a select in the text edit field, that brings up the core keyboard and the text entered there does not propagate back to the text edit field. This also happens under OSX/Kodi.

Is this a known issue ?

**Comment by keithah** [comment]
So essentially the bug is:

If you bring up search and click on the text box, it brings up the system KB, which you can type in, but when you click ok on it, it does not bring the text from the keyboard into the search screen.

I tested on Android and can confirm this as a bug.

**Comment by MrMC** [comment]
it's a little confusing, script-plex-user_select.xml defines both and edit and label control. Then  /lib/windows/search.py and lib/windows/kodigui.py sometimes uses edit, sometimes label.

**Comment by ruuk** [comment]
The edit control is only used to allow typing directly via keyboard, otherwise Kodi will capture characters such as 's' (shutdown), etc. Attempting to get text from the edit control causes Kodi to crash (at least at the time this was implemented) which is why text typed in the system KB is not used. I can check if the crashing issue is fixed in 18, but otherwise (and for previous versions) the fix is either to disable the ability to use the keyboard for typing entirely (i.e. not use the edit control) or to somehow try to prevent the system KB from appearing at all.

**Comment by MrMC** [comment]
Does not crash under MrMC 3.5.1 (in Testflight) or Kodi 17.6 under OSX. The actual GUIeditControl does contain the text from system keyboard.

As for preventing, it's an Edit Control that is focusable. No way to prevent a select to prevent the system keyboard from popping up.

I'd rather fix the real issue, edit controls allow both typed from a real keyboard or virtual keyboard. For the platforms we support, 99 percent of users would never have a keyboard attached.

Sounds like most of your testing is done on desktop rather than embedded :)

**Comment by ruuk** [comment]
> The actual GUIeditControl does contain the text from system keyboard.

Correct, but it's not accessed here because of the issues I mentioned.

Testing `.getText()` just now with 17.6 seems to work fine, so this must have been either only a 16 issue or fixed in a point release. I can't remember what versions I originally had the issues on. In any case I should be able to fix this for 17+

> Sounds like most of your testing is done on desktop rather than embedded :)

Heh, nah - the ability to use the keyboard was requested, otherwise I would have just limited it to the included UI keys and avoided the whole issue :smile:

**Comment by MrMC** [comment]
If you run into issues, let us know. We know the inside core code quite well.

**Comment by ruuk** [comment]
Fixed for next release.

**Comment by MrMC** [comment]
thx, will verify in a bit

**Comment by MrMC** [comment]
verified
