### ISSUE TITLE
OSD stays too long after pressing play

### ISSUE THREAD

**Issue by pannal** [plexinc/plex-for-kodi#172]
Once a video is paused via the pause key (Kodi OSD controls not showing), after pressing play again, the OSD doesn't hide instantly, but takes a good 3 seconds. 

Because the OSD itself isn't transparent, it completely covers subtitles behind it, and makes them invisible.

**Comment by ruuk** [comment]
I can look at this again, but the shadow covers the Kodi OSD and is meant to hide when that does, so if it is hiding at the same time, you wouldn't actually see the subtitles anyway because of the Kodi OSD.

**Comment by pannal** [comment]
The OSD isn't visible when I press pause on my remote, only the backdrop.

**Comment by ruuk** [comment]
To make sure we're talking about the same thing, here's a screenshot. There is the Plex OSD, with the "shadow" underneath, and underneath that is the Kodi OSD which you can't see because of the "shadow". Are you saying the Plex OSD does not display on pause, and if so do you mean specifically only when you use the remote?
![screenshot000](https://user-images.githubusercontent.com/3951023/38054242-3c6b7392-328b-11e8-9c36-0feb543ac980.png)

**Comment by pannal** [comment]
OK, now I understand what you're saying, and then my issue text is wrong again.

Just so that we are on the same page (now), there are three layers:
- the shadow
- the Plex OSD
- the controls (if I use the OK button to pause)

When I use the Pause button on my remote to pause, I see what you see in your screenshot. After pressing Play the video starts playing, but the Plex OSD doesn't hide for another 3 (+?) seconds.

That's the issue, not the shadow, which hides at the same time the Plex OSD hides.

**Comment by pannal** [comment]
Ah, and the Plex OSD is above the Kodi OSD/Controls? Now I understand your first comment.

I'd expect all of those to vanish much faster in order for me to be able to read the subtitles, yes. Preferrably configurable (don't shoot me).

**Comment by ruuk** [comment]
Yeah, what I see (and what it's supposed to do) is that when the Kodi OSD hides (which you can't see) the "shadow" hides and then the Plex OSD hides about 200 ms after that. Basically I don't think there's much we can do here. I can't control when the Kodi OSD hides, only detect that it is visible. It's not perfect, because when the state that I detect that says the Kodi OSD is visible triggers, that is when the Kodi OSD _starts_ it's hide animation. The shadow delays long enough to cover that, and then we hide the Plex OSD. That's not necessarily exactly what happens - it's been a while since I worked on it, but it took a quite of bit of tweaking to get it to hide as fast as possible and still look good.

**Comment by pannal** [comment]
OK, thank you for the explanation.

Auto-Hiding the Kodi OSD regardless of the features of the skin (I belive Estuary does that by itself?) can be done for example using https://github.com/marcelveldt/script.skin.helper.service/wiki/Settings#skinhelperautoclosevideoosd. I'm not sure whether you want to incorporate that into P4K, but something similar would definitely be helpful for subtitle users.

**Comment by ruuk** [comment]
Yeah, maybe I can force that closed there - I don't remember if I tried that or not. All the OSD stuff was a big PITA with a lot of experimentation :smile:

**Comment by pannal** [comment]
[This is the relevant part of the code](https://github.com/marcelveldt/script.skin.helper.service/blob/5038553b48cfd99b14e9aa1585487e24b3877ad8/resources/lib/listitem_monitor.py#L249) I think.

As you've already integrated a busyloop/event watcher system as far as I can tell, that could be easily incorporated there.

Want me to have a go at it?

**Comment by ruuk** [comment]
Feel free, and it would be appreciated. I think it's fine to hide the OSD as soon as possible after playback resumes, as long as it all looks clean (i.e. the Kodi OSD doesn't show for a fraction of a second, etc).

**Comment by pannal** [comment]
So, it turns out, auto-hiding the Kodi OSD with Estuary isn't possible by default and needs an [actual skin modification](https://github.com/pannal/skin.estuary_plex) to achieve that.

**Comment by dannydan412** [comment]
Ideally, shouldn't the subtitles move above the OSD when it's displayed?
That seems to be how other players handle this issue.

**Comment by ruuk** [comment]
That's a question for the Kodi forums. The add-on doesn't have any control over subtitle placement.
