### ISSUE TITLE
Add 'Playlist Previews' when scrolling over the Playlist Section

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#28]
Currently when highlighting the Playlist Section on the main menu its blank underneath. We should populate Playlist Previews here.

(changed Hub to Section, as per ruuk's comments)

**Comment by keithah** [comment]
There's apparently not a nice convenient hubby endpoint to get them all at once, unfortunately...

**Comment by elan** [comment]
The `/hubs` endpoint returns recently listened to playlists (last week). This was done on purpose so that we didn't keep showing playlists the user had no interest in. Generally speaking, clients should not show a hub if it's empty.

**Comment by ruuk** [comment]
I think the issue title is perhaps confusing. It's not the playlist hub but the playlist section. Since the  playlist section is not a library section, it doesn't have a hubs endpoint. With the new interface, that results in every section spring-loading hubs except playlists, which is empty. This lead some users to believe this was a bug.

**Comment by stueeey666** [comment]
not usually one to interfere with such matters... just offering my user perspective here.  (conscious it may not be the right place to do so)

Viewing Playlists... I understand that the thinking behind playlists in general may be more aligned to music than movies.  Personally I use apple music so currently have no way to implement Plex music, that said I would love the Plex UI to implement movie playlists as per the main movie sections (3 rows of posters) rather than a file list with fanart.  Is there no way to make Movie Playlists appear like Movie Sections.  

I use Playlists to create quick links to my fav collections, genres etc and viewing them in a file list is rather unrewarding.  Sure this is possibly not how Plex intended users to use playlists, but I dare say many many user do (I can't be the only one LOL)

**Comment by Enigma0** [comment]
I'd mark this as a bug rather than an enhancement. In every other player, when previewing the Playlists category, it shows what playlists exist. This addon on the other hand just shows blank nothing even when playlists do exist: https://forums.plex.tv/discussion/247520/home-menu-playlist-view-bug

My server has only TV/Movie smart playlists if that helps. I use Google Play Music.

**Comment by keithah** [comment]
@Enigma0 What other player has a preview? I looked at PMP, Web, Roku and Android TV and none of them show anything until you select the section, so I'm not sure what you mean. We are internally discussing what to show, but I'm curious what you mean.

**Comment by Enigma0** [comment]
@keithah Yeah I take that statement back mostly. Android TV does have a Playlists section that when navigated over, shows in order of recent access, a bunch of playlists inline like every other section.

PMP and Web don't and those are the only other ones I can test besides Android TV.

That being said, I thought PMP used to show a Playlists blob on the home screen with the recent ones there but it's no longer there if it was. I also would have expected that line on the Web view - thought it was there before but maybe not.

**Comment by ruuk** [comment]
There is a Recent Playlists hub, but it is part of the 'Home' section.

**Comment by Enigma0** [comment]
@ruuk That sounds like what I'm thinking of. So maybe instead of showing nothing, when mousing over Playlists you just show the same Home hub which has recent playlists and whatever else?

**Comment by ruuk** [comment]
Well, in the latest version we show two 'hubs' - one for video and one for audio playlists instead of nothing. The 'Recent Playlists' hub is part of the endpoint for 'Home' so not really usable here, though I think the same can probably be achieved without using the hubs endpoint.

**Comment by Enigma0** [comment]
Yeah my bad, after looking at the latest it looks like what I had in mind was actually implemented - awesome. As far as I can tell, this ought to be closed as finished, ya?

**Comment by keithah** [comment]
Yup!
