### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by RyanDawkins** [plexinc/plex-for-kodi#284]
Is this project still active? I see the last release 1 year ago. 

Is this project open to taking new pull requests?

**Comment by ruuk** [comment]
I'm busy with other things lately, so not much has been added in a while from me, but the develop branch has had some activity. If a PR fixes something or adds something that is missing but other TV clients have (and is otherwise a decent PR) then that should probably be easy to get in. I'm looking at setting aside some time soon to get some more PRs in and push a new version.
