### ISSUE TITLE
Change my.plexapp.com to plex.tv

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#50]
They said its on different ELB's, so let's try changing it in the app and see if it makes a difference.

**Comment by g1t-dlanor** [comment]
As you will note from my new posts on the authentication failures I've seen when using 'Plex for Kodi' on my Android devices, such a change WILL make a big difference to many users of ad-blocking software, both on Android and other systems, since some maintainers of ad-blocking lists have included "my.plexapp.com" as a site to be blocked.

**Comment by keithah** [comment]
0.0.96 has this change in and has been pushed to repo, so should be updated soon. :)
