### ISSUE TITLE
No Server Found on reboot

### ISSUE THREAD

**Issue by DontCallMeLarry** [plexinc/plex-for-kodi#53]
No servers are found upon automatically into Plex but the server is immediately found when selecting the dropdown.

**Comment by keithah** [comment]
We need a log to see what is happening in situations like this. Sounds like your server is taking a few moments to connect too.

**Comment by ruuk** [comment]
@DontCallMeLarry: Can you try this version and see if it helps?

[script.plex-0.0.100a1.zip](https://github.com/plexinc/plex-for-kodi/files/667044/script.plex-0.0.100a1.zip)

**Comment by DontCallMeLarry** [comment]
Thanks for the file ruuk but I'm not sure how to load those files. Both server and client are running on Ubuntu 16.04.

The log file is [here](http://paste.ubuntu.com/23671162/)
Booting finished at 20:58:31
I re-selected the server dropdown successfully at 21:01:38

**Comment by ruuk** [comment]
Instructions for installing from zip:

http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

**Comment by DontCallMeLarry** [comment]
OK thanks. I installed the zip file and still have the problem. Keep in mind that it works fine if I start the add-on after the system has be up for a minute.  My guess is that it's some sort of race condition where the OS isn't ready for the plex app to start making request.

**Comment by ruuk** [comment]
Thanks!

Now I just need a log with the issue and the new version :)

**Comment by DontCallMeLarry** [comment]
Ah yes, that makes sense doesn't it.
[Here](http://paste.ubuntu.com/23676639/) is the updated log.

**Comment by ruuk** [comment]
Thanks for the log. Looked through it and here's what I found.

First when the add-on is trying to connect to plex.tv or cached servers it's getting this error:
>Temporary failure in name resolution

Then when Kodi itself tries to connect for the RSS feed it gets what amounts to the same error:
>ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
>ERROR: CCurlFile::Open failed with code 0 for http://feeds.kodi.tv/xbmc

So ultimately it looks like DNS on the system isn't ready when Kodi starts, so all connections are failing.

I'm guessing you have this device booting directly into Kodi, and it appears you have the add-on running on startup in Kodi.

We maybe could use a little longer wait when no servers are found, but otherwise this is basically more an issue with the system not being ready.

**Comment by keithah** [comment]
I suggest putting a delay in the start of Kodi, since Kodi itself will have issues without the network being up, and isn't an issue directly related to the add-on. closing this out.
