### ISSUE TITLE
Please follow GitHub release flow

### ISSUE THREAD

**Issue by ptr727** [plexinc/plex-for-kodi#59]
Please follow the GitHub release flow model, i.e. create releases and tags.
https://github.com/blog/1547-release-your-software
https://guides.github.com/introduction/flow/
https://help.github.com/articles/creating-releases/

Please do not use private code branches to release test code, it defeats the purpose having branches, or pull requests, where users are encouraged to test new releases and help resolve issues in a timely manner.
I.e. https://forums.plex.tv/discussion/251413/only-for-serious-testers-bleeding-edge-testing-releases

Please structure your code in a way that allows for easy download as zip, and then deploy via zip in Kodi.

Yes, I know you deleted my post on the forum complaining about the same.
If you do not want to follow GitHub semi-standard release processes, ok, just state so publicly, and I (really we, as I've seen others ask for the same in your other GitHub projects) will live with it :)

**Comment by keithah** [comment]
I deleted your post from the forum because as I said, off topic posts will be deleted. We test in a private branch because we sometimes need to build in features that aren't launched yet. We appreciate people testing the .zips we give them, but honestly we're not interested in folks deploying via github to Kodi. 

I appreciate your feedback, but its unnecessary and not how we operate. If you don't want to use the testing releases, thats fine, just use the ones in the Kodi repo. If you don't want to use that, there's many other Plex clients available you can use as well. :) We're being as open as possible, but github is for code issues, and not things like this. You can bring them up on the forum (not in the testing thread though, where I explicitly said off topic posts will be deleted) and I will response the exact same way.
